### ISSUE TITLE
Support for managing multiple Heroku apps?

### ISSUE THREAD

**Issue by justinthiele** [harrystech/dynosaur-rails#4]
I'm curious what it would take to manage multiple Heroku apps from 1 Dynosaur instance.

As it is now, you need to have a separate Dynosaur for each of your apps, correct?

**Comment by werkshy** [comment]
I'm closing this but it is still a valid request for Dynosaur itself and I opened an issue over there.

https://github.com/harrystech/dynosaur/issues/25
